
# Copyright (C) Igor Sysoev


CFLAGS = -nologo -O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT)

zlib.lib:
	cl -c $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c compress.c

	link -lib -out:zlib.lib adler32.obj crc32.obj deflate.obj \
		trees.obj zutil.obj compress.obj
