
CFLAGS = -nologo -c -MT -O2 -Ob1 -Oi -Gs $(CPU_OPT)

zlib.lib:
	cl $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c

	link -lib -out:zlib.lib adler32.obj crc32.obj deflate.obj \
		trees.obj zutil.obj
