
CFLAGS = -c -zq -bt=nt -ot -op -oi -oe -s -bm $(OWC_OPT)

zlib.lib:
	wcl386 $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c
	wlib -n zlib.lib adler32.obj crc32.obj deflate.obj trees.obj zutil.obj
