
# Copyright (C) Igor Sysoev


CFLAGS = -q -O2 -tWM $(CPU_OPT)

zlib.lib:
	bcc32 -c $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c

	tlib zlib.lib +adler32.obj +crc32.obj +deflate.obj \
		+trees.obj +zutil.obj
