
# Copyright (C) Igor Sysoev


CFLAGS = -q -O2 -tWM -w-8004 -w-8012 $(CPU_OPT)

zlib.lib:
	bcc32 -c $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c \
		compress.c

	tlib zlib.lib +adler32.obj +crc32.obj +deflate.obj \
		+trees.obj +zutil.obj +compress.obj
