
# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.


CFLAGS = -nologo -O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT) -D L_ENDIAN

!IF "$(MD5_ASM)" == "YES"

md5.lib:
	cd $(MD5)
	cl -c $(CFLAGS) -D MD5_ASM md5_dgst.c
	link -lib -out:md5.lib md5_dgst.obj asm/m-win32.obj

!ELSE

md5.lib:
	cd $(MD5)
	cl -c $(CFLAGS) md5_dgst.c
	link -lib -out:md5.lib md5_dgst.obj

!ENDIF
