
# Copyright (C) Igor Sysoev


CFLAGS = -nologo -MT -O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT) -D L_ENDIAN

!if "$(MD5_ASM)" == "YES"

md5.lib:
	cl -c $(CFLAGS) -D MD5_ASM md5_dgst.c
	link -lib -out:md5.lib md5_dgst.obj asm/m-win32.obj

!else

md5.lib:
	cl -c $(CFLAGS) md5_dgst.c
	link -lib -out:md5.lib md5_dgst.obj

!endif
