
CFLAGS = -c -zq -bt=nt -ot -op -oi -oe -s $(OWC_OPT)

md5.lib:
	wcl386 $(CFLAGS) -bm -dL_ENDIAN md5_dgst.c
	wlib -n md5.lib md5_dgst.obj

#md5.lib:
asm:
	wcl386 $(CFLAGS) -bm -dMD5_ASM -dL_ENDIAN md5_dgst.c
	wcl386 $(CFLAGS) asm\m-win32.asm
	wlib -n md5.lib md5_dgst.obj m-win32.obj
