#!/bin/bash

# Exit on any error
set -e

#compile modsec
cd ModSecurity
git submodule init
git submodule update
./build.sh
./configure
make
make install
cd ..

cd vesta-nginx

# compile nginx with modsec dynamic module
./configure --with-compat --add-dynamic-module=../ModSecurity-nginx
make
make install
