---
body:
  - type: markdown
    attributes:
      value: |
        For NGINX troubleshooting/technical help, please visit our community forum instead of asking your questions here. We will politely redirect these types of questions to the forum.
  - type: textarea
    id: ideas
    attributes:
      label: What idea would you like to discuss?
      description: Please provide as much context as possible. Remember that only ideas related to the NGINX codebase will be addressed on GitHub. For anything else, please visit our [community forum](https://community.nginx.org/).
      value: |
        I have an idea for...
    validations:
      required: true
