#ifndef _NGX_HTTP_FILTER_H_INCLUDED_
#define _NGX_HTTP_FILTER_H_INCLUDED_


#define NGX_HTTP_FILTER_ERROR  -1
#define NGX_HTTP_FILTER_AGAIN   0
#define NGX_HTTP_FILTER_DONE    1


#endif /* _NGX_HTTP_FILTER_H_INCLUDED_ */
