
# Copyright (C) Igor Sysoev


CFLAGS = -nologo -O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT) -D L_ENDIAN

!IF "$(SHA1_ASM)" == "YES"

sha1.lib:
	cd $(SHA1)
	cl -c $(CFLAGS) -D SHA1_ASM sha1dgst.c
	link -lib -out:sha1.lib sha1dgst.obj asm/s-win32.obj

!ELSE

sha1.lib:
	cd $(SHA1)
	cl -c $(CFLAGS) sha1dgst.c
	link -lib -out:sha1.lib sha1dgst.obj

!ENDIF
