name: buildbot

on:
  push:
    branches:
      - master
      - 'stable-1.*'

jobs:
  buildbot:
    uses: nginx/ci-self-hosted/.github/workflows/nginx-buildbot.yml@a18ba87ce844172e745b83b6bcfed902c5bbe039 # main
