name: Mark Stale Pull Requests

on:
  schedule:
    - cron: '22 2 * * *'  # Run every day at 02:22

env:
  PR_STALE_DAYS: 180

jobs:
  mark_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Mark stale pull requests
        uses: actions/stale@v5
        with:
          stale-pr-message: "This pull request has been automatically marked 'stale' because it has been inactive for more than ${{ env.PR_STALE_DAYS }} days."
          days-before-stale: ${{ env.PR_STALE_DAYS }}
          days-before-issue-stale: -1
          days-before-close: -1
          stale-pr-label: stale
