name: Set new pull-requests & issues creation date

on:
  issues:
    types:
      - opened
  pull_request:
    branches: master
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.PROJECT_PAT }}

jobs:
  set-issue-date:
    runs-on: ubuntu-latest

    steps:
      - name: Get project data
        env:
          ORGANIZATION: nginx
          PROJECT_NUMBER: 33
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org) {
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2FieldCommon {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER >project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >>$GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name == "Created at") | .id' project_data.json) >>$GITHUB_ENV

      # Needed to get the item's Global ID
      - name: Add pull-request/issue to project
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            PRI_ID=${{ github.event.issue.node_id }}
          else
            PRI_ID=${{ github.event.pull_request.node_id }}
          fi

          item_id="$(gh api graphql -f query='
            mutation($project:ID!, $item:ID!) {
              addProjectV2ItemById(
                input: {
                  projectId: $project, contentId: $item
                }) {
                  item {
                    id
                  }
                }
              }' -f project=$PROJECT_ID -f item=$PRI_ID --jq '.data.addProjectV2ItemById.item.id')"
          echo 'ITEM_ID='$item_id >>$GITHUB_ENV

      - name: Set pull-request/issue creation date
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            DATE=${{ github.event.issue.created_at }}
          else
            DATE=${{ github.event.pull_request.created_at }}
          fi

          gh api graphql -f query='
            mutation(
              $project: ID!
              $item: ID!
              $date_field: ID!
              $date: Date!
            ) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project
                  itemId: $item
                  fieldId: $date_field
                  value: {
                    date: $date
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f date_field=$DATE_FIELD_ID -f date=$DATE
